# Generated by Django 2.1.2 on 2018-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2083)),
                ('state', models.CharField(choices=[('RE', 'Ready'), ('UP', 'Updating'), ('AD', 'Added'), ('ER', 'Error')], default='AD', max_length=2)),
            ],
        ),
    ]
