# Generated by Django 2.1.1 on 2018-10-24 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryStateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('RE', 'Ready'), ('UP', 'Updating'), ('AD', 'Added'), ('ER', 'Error')], default='AD', max_length=2)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='repository',
            name='state',
        ),
        migrations.AddField(
            model_name='repository',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repositorystatechange',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Repository'),
        ),
    ]
