# Generated by Django 2.1.1 on 2018-11-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20181024_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorystatechange',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='repositorystatechange',
            name='state',
            field=models.CharField(choices=[('RE', 'Ready'), ('OU', 'Outdated'), ('UP', 'Updating'), ('AD', 'Added'), ('ER', 'Error')], default='AD', max_length=2),
        ),
    ]
