# Generated by Django 2.1.1 on 2018-11-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20181108_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=32)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='scheduler.Repository')),
            ],
        ),
        migrations.AlterField(
            model_name='repositorystatechange',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='scheduler.Repository'),
        ),
    ]
