# Generated by Django 2.1.5 on 2019-01-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20181108_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='run_id',
        ),
    ]
