# Generated by Django 2.1.5 on 2019-01-29 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_remove_workflow_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='moment',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='state',
            field=models.CharField(choices=[('AD', 'Added'), ('RU', 'Running'), ('ER', 'Error'), ('OK', 'Done')], default='AD', max_length=2),
        ),
    ]
