# Generated by Django 2.1.5 on 2019-01-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20190129_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='cwl_path',
            field=models.CharField(default='bla.cwl', max_length=100),
            preserve_default=False,
        ),
    ]
