# Generated by Django 2.1.5 on 2019-01-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_workflow_cwl_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
