# Generated by Django 2.1.15 on 2019-12-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_workflow_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='command',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
